In [2]:
print(bios.shape)
print(bios.columns.tolist())
bios.head(3)

(145500, 16)
['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC', 'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames', 'Title(s)', 'Other names', 'Nationality', 'Original name', 'Name order']

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN

In [4]:
print(results.shape)
print(results.columns.tolist())
results.head(3)

(308408, 11)
['Games', 'Event', 'Team', 'Pos', 'Medal', 'As', 'athlete_id', 'NOC', 'Discipline', 'Nationality', 'Unnamed: 7']

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN

In [5]:
print(bios_locs.shape)
print(bios_locs.columns.tolist())
bios_locs.head(3)

(145500, 12)
['athlete_id', 'name', 'born_date', 'born_city', 'born_region', 'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date', 'lat', 'long']

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,lat,long
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,44.841225,-0.580036
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,49.004971,1.910084
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,43.471144,-1.552727

In [6]:
print(noc_galli.shape)
print(noc_galli.columns.tolist())
noc_galli.head(3)

(230, 3)
['NOC', 'region', 'notes']

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN

In [7]:
print(poblacion.shape)
print(poblacion.columns.tolist())
poblacion.head(3)

(266, 66)
['Country Name', 'Country Code', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023']

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba,ABW,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,59291.0,59522.0,...,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0,106445.0,106277.0
1,Africa Eastern and Southern,AFE,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,153955516.0,158313235.0,...,583651101.0,600008424.0,616377605.0,632746570.0,649757148.0,667242986.0,685112979.0,702977106.0,720859132.0,739108306.0
2,Afghanistan,AFG,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,9783147.0,10010030.0,...,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0,41128771.0,42239854.0

In [8]:
print(athlete_events.shape)
print(athlete_events.columns.tolist())
athlete_events.head(3)

(271116, 15)
['ID', 'Name', 'Sex', 'Age', 'Height', 'Weight', 'Team', 'NOC', 'Games', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal']

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN

In [9]:
print(noc_kaggle.shape)
print(noc_kaggle.columns.tolist())
noc_kaggle.head(3)

(230, 3)
['NOC', 'region', 'notes']

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN

In [10]:
print(summer.shape)
print(summer.columns.tolist())
summer.head(3)

(252565, 11)
['player_id', 'Name', 'Sex', 'Team', 'NOC', 'Year', 'Season', 'City', 'Sport', 'Event', 'Medal']

,player_id,Name,Sex,Team,NOC,Year,Season,City,Sport,Event,Medal
0,0,A Dijiang,M,China,CHN,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,No medal
1,1,A Lamusi,M,China,CHN,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,No medal
2,2,Gunnar Aaby,M,Denmark,DEN,1920,Summer,Antwerpen,Football,Football Men's Football,No medal

In [11]:
print(datacamp.shape)
print(datacamp.columns.tolist())
datacamp.head(3)

(271116, 15)
['id', 'name', 'sex', 'age', 'height', 'weight', 'team', 'noc', 'games', 'year', 'season', 'city', 'sport', 'event', 'medal']

,id,name,sex,age,height,weight,team,noc,games,year,season,city,sport,event,medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN

In [3]:
import pandas as pd

bios = pd.read_csv('../raw/bios.csv')
results = pd.read_csv('../raw/results.csv')
bios_locs = pd.read_csv('../raw/bios_locs.csv')
noc_galli = pd.read_csv('../raw/noc_regions.csv')
poblacion = pd.read_csv('../raw/populations.csv')

athlete_events = pd.read_csv('../raw/kaggle_athlete_events.csv')
noc_kaggle = pd.read_csv('../raw/kaggle_noc_regions.csv')

summer = pd.read_csv('../raw/kaggle_olympics_dataset.csv')

datacamp = pd.read_csv('../raw/datacamp_athlete_events.csv.gz', compression='gzip')

C:\Users\xespi\AppData\Local\Temp\ipykernel_21488\3466979941.py:4: DtypeWarning: Columns (0: Nationality) have mixed types. Specify dtype option on import or set low_memory=False.
  results = pd.read_csv('../raw/results.csv')

In [12]:
print("Medal - results.csv:", results['Medal'].unique())
print("Medal - athlete_events.csv:", athlete_events['Medal'].unique())
print("Medal - summer:", summer['Medal'].unique())
print("Medal - datacamp:", datacamp['medal'].unique())

Medal - results.csv: <StringArray>
[nan, 'Bronze', 'Silver', 'Gold']
Length: 4, dtype: str
Medal - athlete_events.csv: <StringArray>
[nan, 'Gold', 'Bronze', 'Silver']
Length: 4, dtype: str
Medal - summer: <StringArray>
['No medal', 'Gold', 'Bronze', 'Silver']
Length: 4, dtype: str
Medal - datacamp: <StringArray>
[nan, 'Gold', 'Bronze', 'Silver']
Length: 4, dtype: str

In [13]:
set_galli = set(noc_galli['NOC'].dropna().unique())
set_kaggle = set(noc_kaggle['NOC'].dropna().unique())

print("¿Son exactamente el mismo catálogo?", set_galli == set_kaggle)
print("Códigos solo en Galli:", set_galli - set_kaggle)
print("Códigos solo en Kaggle:", set_kaggle - set_galli)

¿Son exactamente el mismo catálogo? True
Códigos solo en Galli: set()
Códigos solo en Kaggle: set()

In [15]:
print(bios_locs[bios_locs['name'] == 'Ivan Ivanov'][['athlete_id', 'name', 'NOC', 'born_date']])

        athlete_id         name           NOC   born_date
358            359  Ivan Ivanov      Bulgaria  1956-06-10
724            728  Ivan Ivanov      Bulgaria  1966-02-19
29273        29488  Ivan Ivanov      Bulgaria  1974-09-26
41116        41431  Ivan Ivanov      Bulgaria  1921-12-06
51443        51802  Ivan Ivanov      Bulgaria  1950-11-19
54900        55295  Ivan Ivanov      Bulgaria  1971-08-27
57003        57409  Ivan Ivanov      Bulgaria  1968-12-19
57004        57410  Ivan Ivanov      Bulgaria  1937-04-24
76869        77459  Ivan Ivanov  Soviet Union  1948-06-26
92846        93591  Ivan Ivanov    Kyrgyzstan  1979-04-27
115850      117219  Ivan Ivanov      Bulgaria  1986-08-24
131994      134837  Ivan Ivanov    Kazakhstan  1992-01-03
133271      136209  Ivan Ivanov       Ukraine  1989-01-08

In [16]:
conteo_equipo = results.groupby(['Discipline', 'Event', 'Games', 'Medal'], dropna=True).size().sort_values(ascending=False)
print(conteo_equipo.head(15))

Discipline                        Event                                           Games                 Medal
Artistic Gymnastics (Gymnastics)  Team All-Around, Men (Olympic)                  1908 Summer Olympics  Gold      37
Football (Football)               Football, Men (Olympic)                         1972 Summer Olympics  Bronze    36
Rugby (Rugby)                     Rugby, Men (Olympic)                            1900 Summer Olympics  Silver    30
Artistic Gymnastics (Gymnastics)  Team All-Around, Men (Olympic)                  1908 Summer Olympics  Silver    29
                                  Team All-Around, Swedish System, Men (Olympic)  1912 Summer Olympics  Silver    28
                                  Team All-Around, Men (Olympic)                  1920 Summer Olympics  Gold      27
                                  Team All-Around, Free System, Men (Olympic)     1920 Summer Olympics  Silver    26
                                  Team All-Around, Men (Olympic)                  1920 Summer Olympics  Bronze    26
                                  Team All-Around, Swedish System, Men (Olympic)  1920 Summer Olympics  Silver    25
Baseball (Baseball/Softball)      Baseball, Men (Olympic)                         2000 Summer Olympics  Gold      24
                                                                                  2004 Summer Olympics  Silver    24
                                                                                  2000 Summer Olympics  Silver    24
                                                                                  2004 Summer Olympics  Bronze    24
                                                                                                        Gold      24
                                                                                  2000 Summer Olympics  Bronze    24
dtype: int64

In [17]:
print("bios_locs:")
print(bios_locs.isnull().sum())
print()
print("athlete_events:")
print(athlete_events.isnull().sum())

bios_locs:
athlete_id           0
name                 0
born_date         1807
born_city        34592
born_region      34592
born_country     34592
NOC                  1
height_cm        38849
weight_kg        43430
died_date       111560
lat              75955
long             75955
dtype: int64

athlete_events:
ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [18]:
print("EVENTO.nombre — largo máximo encontrado:")
print(results['Event'].astype(str).str.len().max())
print(athlete_events['Event'].astype(str).str.len().max())

print("DEPORTE.nombre — largo máximo encontrado:")
print(results['Discipline'].astype(str).str.len().max())
print(athlete_events['Sport'].astype(str).str.len().max())

print("ATLETA.nombre — largo máximo encontrado:")
print(bios_locs['name'].astype(str).str.len().max())
print(athlete_events['Name'].astype(str).str.len().max())

print("PAIS.codigo_noc — largo máximo encontrado:")
print(athlete_events['NOC'].astype(str).str.len().max())

EVENTO.nombre — largo máximo encontrado:
157
85
DEPORTE.nombre — largo máximo encontrado:
35.0
25
ATLETA.nombre — largo máximo encontrado:
49
108
PAIS.codigo_noc — largo máximo encontrado:
3

In [19]:
sedes = athlete_events[['City','Year','Season']].drop_duplicates().sort_values('Year')
print(len(sedes))
print(sedes.to_string())

52
                        City  Year  Season
3079                  Athina  1896  Summer
3                      Paris  1900  Summer
711                St. Louis  1904  Summer
268                   Athina  1906  Summer
1149                  London  1908  Summer
35                 Stockholm  1912  Summer
2                  Antwerpen  1920  Summer
39                     Paris  1924  Summer
672                 Chamonix  1924  Winter
133                Amsterdam  1928  Summer
935             Sankt Moritz  1928  Winter
1326             Lake Placid  1932  Winter
26               Los Angeles  1932  Summer
94                    Berlin  1936  Summer
1327  Garmisch-Partenkirchen  1936  Winter
41                    London  1948  Summer
1187            Sankt Moritz  1948  Winter
29                  Helsinki  1952  Summer
110                     Oslo  1952  Winter
111        Cortina d'Ampezzo  1956  Winter
128                Melbourne  1956  Summer
6194               Stockholm  1956  Summer
83              Squaw Valley  1960  Winter
129                     Roma  1960  Summer
192                    Tokyo  1964  Summer
85                 Innsbruck  1964  Winter
89               Mexico City  1968  Summer
266                 Grenoble  1968  Winter
626                  Sapporo  1972  Winter
90                    Munich  1972  Summer
145                 Montreal  1976  Summer
628                Innsbruck  1976  Winter
188                   Moskva  1980  Summer
30               Lake Placid  1980  Winter
87                  Sarajevo  1984  Winter
88               Los Angeles  1984  Summer
4                    Calgary  1988  Winter
91                     Seoul  1988  Summer
0                  Barcelona  1992  Summer
6                Albertville  1992  Winter
8                Lillehammer  1994  Winter
32                   Atlanta  1996  Summer
68                    Nagano  1998  Winter
31                    Sydney  2000  Summer
28            Salt Lake City  2002  Winter
82                    Athina  2004  Summer
77                    Torino  2006  Winter
79                   Beijing  2008  Summer
245                Vancouver  2010  Winter
1                     London  2012  Summer
40                     Sochi  2014  Winter
80            Rio de Janeiro  2016  Summer